#!/usr/bin/env bash

set -u

function create-master() {

    local template_url="${1:-https://s3.amazonaws.com/baseline.aws.talend.com/templates/talend_master.template.json}"
    local stack_name="${2:-talend-quickstart}"

    aws cloudformation create-stack \
        --stack-name "${stack_name}" \
        --template-url "${template_url}" \
        --parameters \
            ParameterKey=KeyName,ParameterValue= \
            ParameterKey=TalendLicenseUser,ParameterValue= \
            ParameterKey=TalendLicensePassword,ParameterValue= \
            ParameterKey=TalendLicenseUrl,ParameterValue= \
            ParameterKey=TalendResourceBucket,ParameterValue= \
            ParameterKey=TalendResourceBucketRepoPath,ParameterValue=/ \
            ParameterKey=TalendResourceBucketAccessKey,ParameterValue= \
            ParameterKey=TalendResourceBucketSecret,ParameterValue= \
            ParameterKey=talendTacDbHost,ParameterValue= \
            ParameterKey=talendGitHost,ParameterValue=github.com \
            ParameterKey=talendGitPort,ParameterValue=443 \
            ParameterKey=talendGitRepo,ParameterValue= \
            ParameterKey=talendGitUser,ParameterValue= \
            ParameterKey=talendGitPassword,ParameterValue= \
            ParameterKey=createNetworkStack,ParameterValue=true \
            ParameterKey=createNexusStack,ParameterValue=true \
            ParameterKey=createLogserverStack,ParameterValue=true \
            ParameterKey=createTacStack,ParameterValue=true \
            ParameterKey=createJobserverStack,ParameterValue=true \
        --disable-rollback \
        --tags Key=Name,Value="${stack_name}"

}

create-master "${@}"
