#!/usr/bin/env bash

set -u


function create-network() {

    local inbound_cidr="${1:-96.86.40.27/32}"
    local template_url="${2:-https://s3.amazonaws.com/baseline.aws.talend.com/templates/talend_network.template.json}"
    local stack_name="${3:-eost-quickstart-network}"

    aws cloudformation create-stack \
        --stack-name "${stack_name}" \
        --template-url "${template_url}" \
        --parameters \
            ParameterKey=SSHLocation,ParameterValue= \
            ParameterKey=TalendVpcCIDR,ParameterValue=10.0.0.0/16 \
            ParameterKey=TalendPublicSubnetCIDR,ParameterValue=10.0.128.0/20 \
            ParameterKey=TalendPrivateSubnetCIDR,ParameterValue=10.0.0.0/19 \
        --disable-rollback \
        --tags Key=Name,Value="${stack_name}"
}


create-network "${@}"
