#!/usr/bin/env bash

set -u

source cfn-util.sh


function create-jobserver() {

    local network_stack="${1:-eost-quickstart-network}"
    local logserver_stack="${2:-eost-quickstart-logserver}"
    local tac_stack="${3:-eost-quickstart-tac}"
    local template_url="${4:-https://s3.amazonaws.com/baseline.aws.talend.com/templates/talend_jobserver.template.json}"
    local stack_name="${5:-eost-quickstart-jobserver}"
    local profile="${6:-jobserver}"

    # network stack dependencies
    aws cloudformation describe-stacks \
        --stack-name "${network_stack}" \
        > "${network_stack}.json"

    local publicSubnet
    getOutput "${network_stack}.json" "publicSubnet"

    local tacSecurityGroup
    getOutput "${network_stack}.json" "tacSecurityGroup"

    # tac stack dependencies
    aws cloudformation describe-stacks \
        --stack-name "${tac_stack}" \
        > "${tac_stack}.json"

    local tac_privateDnsName
    getOutput "${tac_stack}.json" "privateDnsName" "tac_privateDnsName"

    # logserver stack dependencies
    aws cloudformation describe-stacks \
        --stack-name "${logserver_stack}" \
        > "${logserver_stack}.json"

    local logserver_privateDnsName
    getOutput "${logserver_stack}.json" "privateDnsName" "logserver_privateDnsName"



    aws cloudformation create-stack \
        --stack-name "${stack_name}" \
        --template-url "${template_url}" \
        --parameters \
            ParameterKey=InstanceType,ParameterValue=t2.micro \
            ParameterKey=KeyName,ParameterValue= \
            ParameterKey=SubnetId,ParameterValue="${publicSubnet}" \
            ParameterKey=IsPrivateSubnet,ParameterValue=public \
            ParameterKey=SecurityGroupIds,ParameterValue="${tacSecurityGroup}" \
            ParameterKey=TalendProfile,ParameterValue="${profile}" \
            ParameterKey=TalendProfileInstanceId,ParameterValue=1 \
            ParameterKey=TalendLicenseUser,ParameterValue= \
            ParameterKey=TalendLicensePassword,ParameterValue= \
            ParameterKey=TalendLicenseUrl,ParameterValue= \
            ParameterKey=TalendResourceBucket,ParameterValue= \
            ParameterKey=TalendResourceBucketRepoPath,ParameterValue=/ \
            ParameterKey=TalendResourceBucketAccessKey,ParameterValue= \
            ParameterKey=TalendResourceBucketSecret,ParameterValue= \
            ParameterKey=tacHost,ParameterValue="${tac_privateDnsName}" \
            ParameterKey=talendLoggingHost,ParameterValue="${logserver_privateDnsName}" \
            ParameterKey=talendLogstashJobserverPort,ParameterValue=8055 \
        --disable-rollback \
        --tags Key=Name,Value="${stack_name}"

}

create-jobserver "${@}"
